### ISSUE TITLE
Change tag in title to be label inside

### ISSUE THREAD

**Issue by Radoslaw-Kruk** [kabot-io/kabot-s3-firmware#19]

**Comment by Radoslaw-Kruk** [comment]
The task was done. I would like someone to test it.

**Comment by kpochwala** [comment]
I'd remove emoji from title and use labels only. What others think? It looks too funky (nonserious) to me.  Can be seen here: https://github.com/kabot-io/containers/issues

**Comment by kpochwala** [comment]
btw, i dont know what are those labels, might be good to investigate, and remove if not used:



![Image](https://github.com/kabot-io/kabot-s3-firmware/assets/17093535/62778dca-ceac-4707-987a-f640c6835e48)
